<?xml version="1.0"?>

<!DOCTYPE searchresults [
        <!ELEMENT course (clbid, coursestatus, deptname, coursenumber, coursesection, coursesubtype, coursename, pn, notes, instructors, halfcredit, credits, meetingtimes, gereqs, meetinglocations, varcredits, groupid, grouptype)>
	<!ELEMENT clbid (#PCDATA)>
	<!ELEMENT coursestatus (#PCDATA)>
	<!ELEMENT coursename (#PCDATA)>
	<!ELEMENT deptname (#PCDATA)>
	<!ELEMENT coursesection (#PCDATA)>
	<!ELEMENT coursesubtype (#PCDATA)>
	<!ELEMENT pn (#PCDATA)>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT instructors (#PCDATA)>
	<!ELEMENT halfcredit (#PCDATA)>
	<!ELEMENT credits (#PCDATA)>
	<!ELEMENT meetingtimes (#PCDATA)>
	<!ELEMENT gereqs (#PCDATA)>
	<!ELEMENT meetinglocations (#PCDATA)>
	<!ELEMENT varcredits (#PCDATA)>
	<!ELEMENT groupid (#PCDATA)>
	<!ELEMENT grouptype (#PCDATA)>
	<!ELEMENT crsid (#PCDATA)>
]>
<searchresults>




	<course>
	<clbid>0000025069</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>247</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Organic Chemistry</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6161&apos;)"&gt;Pearson, Wesley&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC378&apos;);"&gt;SC 378&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000196</crsid>
	</course>




	<course>
	<clbid>0000025070</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>253</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>L</coursesubtype>
	<coursename>Synthesis Lab</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6161&apos;)"&gt;Pearson, Wesley&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>MT 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC311&apos;);"&gt;SC 311&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000199</crsid>
	</course>




	<course>
	<clbid>0000025071</clbid>
	<coursestatus>O</coursestatus>
	<deptname>EDUC</deptname>
	<coursenumber>382</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Human Relations</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000341</crsid>
	</course>




	<course>
	<clbid>0000025072</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>247</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Post-Colonial Lit</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5144&apos;)"&gt;Mbele, Joseph L.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L520&apos;);"&gt;L 520&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000411</crsid>
	</course>




	<course>
	<clbid>0000025073</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>257</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Creative Writing I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000418</crsid>
	</course>




	<course>
	<clbid>0000025074</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>347</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>T</coursesubtype>
	<coursename>Post-Col/3rd Wld Lit</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5144&apos;)"&gt;Mbele, Joseph L.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L520&apos;);"&gt;L 520&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000438</crsid>
	</course>




	<course>
	<clbid>0000025075</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENVST</deptname>
	<coursenumber>150</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Minn Natural History</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001728</crsid>
	</course>




	<course>
	<clbid>0000025076</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENVST</deptname>
	<coursenumber>232</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Enviro Policy/Regulat</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000459</crsid>
	</course>




	<course>
	<clbid>0000025077</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENVST</deptname>
	<coursenumber>237</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Intro: Enviro Studies</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001729</crsid>
	</course>




	<course>
	<clbid>0000025078</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENVST</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Trail Erosion Stdy</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1355&apos;)"&gt;Deason, Gary&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000465</crsid>
	</course>




	<course>
	<clbid>0000025082</clbid>
	<coursestatus>O</coursestatus>
	<deptname>FAMST</deptname>
	<coursenumber>242</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Family Relationships</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;3431&apos;)"&gt;Holt, C. George&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;H209&apos;);"&gt;H 209&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000649</crsid>
	</course>




	<course>
	<clbid>0000025083</clbid>
	<coursestatus>O</coursestatus>
	<deptname>FAMST</deptname>
	<coursenumber>253</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Human Sexuality</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;3431&apos;)"&gt;Holt, C. George&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;H209&apos;);"&gt;H 209&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000651</crsid>
	</course>




	<course>
	<clbid>0000025079</clbid>
	<coursestatus>O</coursestatus>
	<deptname>GERM</deptname>
	<coursenumber>231</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Intermed German I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6671&apos;)"&gt;Rippley, Lavern&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000508</crsid>
	</course>




	<course>
	<clbid>0000025080</clbid>
	<coursestatus>O</coursestatus>
	<deptname>HIST</deptname>
	<coursenumber>206</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>U.S. Since 1865</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L420&apos;);"&gt;L 420&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001820</crsid>
	</course>




	<course>
	<clbid>0000025081</clbid>
	<coursestatus>O</coursestatus>
	<deptname>HIST</deptname>
	<coursenumber>246</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Amer Environmental</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1355&apos;)"&gt;Deason, Gary&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000617</crsid>
	</course>




	<course>
	<clbid>0000025084</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MATH</deptname>
	<coursenumber>244</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Elem Real Analysis</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7327&apos;)"&gt;Schwartz, Christopher&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC184&apos;);"&gt;SC 184&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000745</crsid>
	</course>




	<course>
	<clbid>0000025085</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MUSIC</deptname>
	<coursenumber>130</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>The Music Spectrum</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2241&apos;)"&gt;Forsberg, Charles&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;CHM222/224&apos;);"&gt;CHM 222/224&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000803</crsid>
	</course>




	<course>
	<clbid>0000025086</clbid>
	<coursestatus>C</coursestatus>
	<deptname>MUSIC</deptname>
	<coursenumber>165</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Basic Instr Technique</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001960</crsid>
	</course>




	<course>
	<clbid>0000025087</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MUSIC</deptname>
	<coursenumber>222</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Counterpoint</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2241&apos;)"&gt;Forsberg, Charles&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000821</crsid>
	</course>




	<course>
	<clbid>0000025088</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MUSIC</deptname>
	<coursenumber>223</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Composition I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2241&apos;)"&gt;Forsberg, Charles&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;CHM232&apos;);"&gt;CHM 232&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000822</crsid>
	</course>




	<course>
	<clbid>0000025089</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MUSIC</deptname>
	<coursenumber>324</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Composition II</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2241&apos;)"&gt;Forsberg, Charles&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;CHM239&apos;);"&gt;CHM 239&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000851</crsid>
	</course>




	<course>
	<clbid>0000025093</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>100</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Individualized Phy Ed</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000995</crsid>
	</course>




	<course>
	<clbid>0000025094</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>100</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Individualized Phy Ed</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000995</crsid>
	</course>




	<course>
	<clbid>0000025095</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>125</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Canoeing</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1355&apos;)"&gt;Deason, Gary&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001007</crsid>
	</course>




	<course>
	<clbid>0000025096</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>132</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Individual Fitness</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1358&apos;)"&gt;Daymont, Christine&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0300-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;6/01SKOGLND&apos;);"&gt;6/01 SKOGLND&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000002185</crsid>
	</course>




	<course>
	<clbid>0000025097</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>140</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Wt Training Co-Ed .25</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1358&apos;)"&gt;Daymont, Christine&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0300-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;6/01SKOGLND&apos;);"&gt;6/01 SKOGLND&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001016</crsid>
	</course>




	<course>
	<clbid>0000025090</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PHIL</deptname>
	<coursenumber>241</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Phil. Theology</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6392&apos;)"&gt;Poling, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L421&apos;);"&gt;L 421&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000973</crsid>
	</course>




	<course>
	<clbid>0000025091</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PHIL</deptname>
	<coursenumber>252</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Ethics/The Good Life</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6392&apos;)"&gt;Poling, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L421&apos;);"&gt;L 421&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000979</crsid>
	</course>




	<course>
	<clbid>0000025092</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PHIL</deptname>
	<coursenumber>257</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Top: Environ Ethics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2022&apos;)"&gt;Fairbanks, Rick A.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000982</crsid>
	</course>




	<course>
	<clbid>0000025098</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PHYS</deptname>
	<coursenumber>124</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Principles Physics I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5620&apos;)"&gt;Nitz, David&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130&lt;br&gt;WF 0100-0330PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC170&apos;);"&gt;SC 170&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC111&apos;);"&gt;SC 111&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001072</crsid>
	</course>




	<course>
	<clbid>0000025099</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSYCH</deptname>
	<coursenumber>121</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Principles: Psych</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;H204&apos;);"&gt;H 204&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001154</crsid>
	</course>




	<course>
	<clbid>0000025100</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSYCH</deptname>
	<coursenumber>238</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Biopsychology</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;H204&apos;);"&gt;H 204&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001165</crsid>
	</course>




	<course>
	<clbid>0000025101</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>221</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Jesus in Script/Trad</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;3061&apos;)"&gt;Hanson, James&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L577&apos;);"&gt;L 577&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001205</crsid>
	</course>
</searchresults>