<?xml version="1.0"?>

<!DOCTYPE searchresults [
        <!ELEMENT course (clbid, coursestatus, deptname, coursenumber, coursesection, coursesubtype, coursename, pn, notes, instructors, halfcredit, credits, meetingtimes, gereqs, meetinglocations, varcredits, groupid, grouptype)>
	<!ELEMENT clbid (#PCDATA)>
	<!ELEMENT coursestatus (#PCDATA)>
	<!ELEMENT coursename (#PCDATA)>
	<!ELEMENT deptname (#PCDATA)>
	<!ELEMENT coursesection (#PCDATA)>
	<!ELEMENT coursesubtype (#PCDATA)>
	<!ELEMENT pn (#PCDATA)>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT instructors (#PCDATA)>
	<!ELEMENT halfcredit (#PCDATA)>
	<!ELEMENT credits (#PCDATA)>
	<!ELEMENT meetingtimes (#PCDATA)>
	<!ELEMENT gereqs (#PCDATA)>
	<!ELEMENT meetinglocations (#PCDATA)>
	<!ELEMENT varcredits (#PCDATA)>
	<!ELEMENT groupid (#PCDATA)>
	<!ELEMENT grouptype (#PCDATA)>
	<!ELEMENT crsid (#PCDATA)>
]>
<searchresults>




	<course>
	<clbid>0000025184</clbid>
	<coursestatus>C</coursestatus>
	<deptname>AMST</deptname>
	<coursenumber>100</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Perspec Amer Culture</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2030&apos;)"&gt;Farrell, James&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L177&apos;);"&gt;L 177&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000004</crsid>
	</course>




	<course>
	<clbid>0000025950</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ARMS</deptname>
	<coursenumber>121</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Intro to Arms</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2113&apos;)"&gt;Fitzgerald, Michael&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;3322&apos;)"&gt;Hepburn, Joan&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L577&apos;);"&gt;L 577&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001482</crsid>
	</course>




	<course>
	<clbid>0000025185</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>111</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Perceptual Draw</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7064&apos;)"&gt;Saurer, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0120-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH42&apos;);"&gt;FH 42&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000019</crsid>
	</course>




	<course>
	<clbid>0000025186</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>111</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Perceptual Draw</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7064&apos;)"&gt;Saurer, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0305-0430PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH42&apos;);"&gt;FH 42&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000019</crsid>
	</course>




	<course>
	<clbid>0000025187</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>112</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Conceptual Draw</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7486&apos;)"&gt;Shoger, Jan&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0200-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH42&apos;);"&gt;FH 42&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000020</crsid>
	</course>




	<course>
	<clbid>0000025190</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>114</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Foundation Sculpture</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7064&apos;)"&gt;Saurer, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0800-0925</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH18&apos;);"&gt;FH 18&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000022</crsid>
	</course>




	<course>
	<clbid>0000025191</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>114</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Foundation Sculpture</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7064&apos;)"&gt;Saurer, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0935-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH18&apos;);"&gt;FH 18&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000022</crsid>
	</course>




	<course>
	<clbid>0000025192</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>116</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Ceramics: Hand</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0935-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH19&apos;);"&gt;FH 19&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000024</crsid>
	</course>




	<course>
	<clbid>0000025193</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>119</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Ceramics: Wheel</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0110PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH19&apos;);"&gt;FH 19&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000026</crsid>
	</course>




	<course>
	<clbid>0000025194</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>119</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Ceramics: Wheel</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0120-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH19&apos;);"&gt;FH 19&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000026</crsid>
	</course>




	<course>
	<clbid>0000025195</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>120</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Honors Found Drawing</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7486&apos;)"&gt;Shoger, Jan&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0800-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH42&apos;);"&gt;FH 42&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000027</crsid>
	</course>




	<course>
	<clbid>0000025196</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>124</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Photography</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5816&apos;)"&gt;Ojala, Margaret&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0800-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH2&apos;);"&gt;FH 2&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000029</crsid>
	</course>




	<course>
	<clbid>0000025197</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>150</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Ancient--Medieval</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5286&apos;)"&gt;Michelli, Perette&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0200-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH01&apos;);"&gt;FH 01&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000031</crsid>
	</course>




	<course>
	<clbid>0000025198</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>151</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Renaissance--Present</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5286&apos;)"&gt;Michelli, Perette&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0800-0925</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH01&apos;);"&gt;FH 01&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000032</crsid>
	</course>




	<course>
	<clbid>0000025199</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>231</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Oil/Acrylic Paintng</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2757&apos;)"&gt;Griep, Mary&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1255-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH40&apos;);"&gt;FH 40&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000033</crsid>
	</course>




	<course>
	<clbid>0000025200</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>233</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Sculpt: Metal Casting</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1369&apos;)"&gt;Dell, Irve&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH18&apos;);"&gt;FH 18&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000035</crsid>
	</course>




	<course>
	<clbid>0000025201</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>235</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Arch Drawing/Design I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1564&apos;)"&gt;Edwins, Steven&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1255-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FHAB&apos;);"&gt;FH AB&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000037</crsid>
	</course>




	<course>
	<clbid>0000025202</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>236</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Printmkg: Relief/Litho</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7486&apos;)"&gt;Shoger, Jan&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1045-1245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH44&apos;);"&gt;FH 44&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000038</crsid>
	</course>




	<course>
	<clbid>0000025204</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>248</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Photography</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5816&apos;)"&gt;Ojala, Margaret&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH2&apos;);"&gt;FH 2&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000046</crsid>
	</course>




	<course>
	<clbid>0000025205</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>252</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>High Modernism</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6758&apos;)"&gt;Rohn, Matthew&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1045-1140</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH01&apos;);"&gt;FH 01&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000051</crsid>
	</course>




	<course>
	<clbid>0000025206</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>254</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Italian Renaissance</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5286&apos;)"&gt;Michelli, Perette&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH01&apos;);"&gt;FH 01&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000053</crsid>
	</course>




	<course>
	<clbid>0000025207</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>259</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Art of China/Japan</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2641&apos;)"&gt;Gimse, A. Malcolm&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1255-0150PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH01&apos;);"&gt;FH 01&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000057</crsid>
	</course>




	<course>
	<clbid>0000025208</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>261</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>World Architecture</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2641&apos;)"&gt;Gimse, A. Malcolm&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0120-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH01&apos;);"&gt;FH 01&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000059</crsid>
	</course>




	<course>
	<clbid>0000025209</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>270</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Issues Art Criticism</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6758&apos;)"&gt;Rohn, Matthew&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0120-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FHSEM&apos;);"&gt;FH SEM&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000064</crsid>
	</course>




	<course>
	<clbid>0000025211</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Ceramic Process</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000025213</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Model 3d Animation</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5816&apos;)"&gt;Ojala, Margaret&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000025214</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>331</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Painting II</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2757&apos;)"&gt;Griep, Mary&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1255-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH40&apos;);"&gt;FH 40&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001512</crsid>
	</course>




	<course>
	<clbid>0000025215</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>333</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Sculpture II</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1369&apos;)"&gt;Dell, Irve&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH18&apos;);"&gt;FH 18&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001513</crsid>
	</course>




	<course>
	<clbid>0000025216</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>348</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Photography II</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5816&apos;)"&gt;Ojala, Margaret&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH2&apos;);"&gt;FH 2&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001516</crsid>
	</course>




	<course>
	<clbid>0000025217</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>398</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IR/Soda Fired Ceramic</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000075</crsid>
	</course>




	<course>
	<clbid>0000025218</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>398</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IR/Advanced Ceramics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000075</crsid>
	</course>




	<course>
	<clbid>0000025219</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>111</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Family &amp;amp; Self/E Asia</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6625&apos;)"&gt;Reed, Barbara&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0110PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;CH109&apos;);"&gt;CH 109&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000076</crsid>
	</course>




	<course>
	<clbid>0000025220</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Calligraphy</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2641&apos;)"&gt;Gimse, A. Malcolm&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000094</crsid>
	</course>




	<course>
	<clbid>0000025221</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>398</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IR/Archival Research</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;656&apos;)"&gt;Bodman, Richard&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000097</crsid>
	</course>




	<course>
	<clbid>0000025222</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>399</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>S</coursesubtype>
	<coursename>Asia Seminar</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1821&apos;)"&gt;Entenmann, Robert&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0935-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;M30&apos;);"&gt;M 30&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000098</crsid>
	</course>




	<course>
	<clbid>0000025223</clbid>
	<coursestatus>C</coursestatus>
	<deptname>BIO</deptname>
	<coursenumber>123</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Human Biology</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;10506&apos;)"&gt;Gill, Jagjit&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000&lt;br&gt;W 0200-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC280&apos;);"&gt;SC 280&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC253&apos;);"&gt;SC 253&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000102</crsid>
	</course>




	<course>
	<clbid>0000025224</clbid>
	<coursestatus>C</coursestatus>
	<deptname>BIO</deptname>
	<coursenumber>123</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Human Biology</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;10506&apos;)"&gt;Gill, Jagjit&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000&lt;br&gt;Th 0800-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC280&apos;);"&gt;SC 280&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC253&apos;);"&gt;SC 253&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000102</crsid>
	</course>




	<course>