<?xml version="1.0"?>

<!DOCTYPE searchresults [
        <!ELEMENT course (clbid, coursestatus, deptname, coursenumber, coursesection, coursesubtype, coursename, pn, notes, instructors, halfcredit, credits, meetingtimes, gereqs, meetinglocations, varcredits, groupid, grouptype)>
	<!ELEMENT clbid (#PCDATA)>
	<!ELEMENT coursestatus (#PCDATA)>
	<!ELEMENT coursename (#PCDATA)>
	<!ELEMENT deptname (#PCDATA)>
	<!ELEMENT coursesection (#PCDATA)>
	<!ELEMENT coursesubtype (#PCDATA)>
	<!ELEMENT pn (#PCDATA)>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT instructors (#PCDATA)>
	<!ELEMENT halfcredit (#PCDATA)>
	<!ELEMENT credits (#PCDATA)>
	<!ELEMENT meetingtimes (#PCDATA)>
	<!ELEMENT gereqs (#PCDATA)>
	<!ELEMENT meetinglocations (#PCDATA)>
	<!ELEMENT varcredits (#PCDATA)>
	<!ELEMENT groupid (#PCDATA)>
	<!ELEMENT grouptype (#PCDATA)>
	<!ELEMENT crsid (#PCDATA)>
]>
<searchresults>




	<course>
	<clbid>0000002909</clbid>
	<coursestatus>C</coursestatus>
	<deptname>AMCON</deptname>
	<coursenumber>102</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Dem Vistas: 1800-1900</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;3424&apos;)"&gt;Holly, Carol&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1045-1140</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L515&apos;);"&gt;L 515&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000177</crsid>
	</course>




	<course>
	<clbid>0000002910</clbid>
	<coursestatus>C</coursestatus>
	<deptname>AMCON</deptname>
	<coursenumber>102</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Dem Vistas: 1800-1900</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;110&apos;)"&gt;Allister, Mark&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1045-1140</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L421&apos;);"&gt;L 421&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000177</crsid>
	</course>




	<course>
	<clbid>0000002911</clbid>
	<coursestatus>C</coursestatus>
	<deptname>AMCON</deptname>
	<coursenumber>202</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Pur/Happiness: 1920-00</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;8415&apos;)"&gt;Titus, Mary&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L515&apos;);"&gt;L 515&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000179</crsid>
	</course>




	<course>
	<clbid>0000002912</clbid>
	<coursestatus>C</coursestatus>
	<deptname>AMCON</deptname>
	<coursenumber>202</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Pur/Happiness: 1920-00</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;4583&apos;)"&gt;Kutulas, Judy&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L515&apos;);"&gt;L 515&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000179</crsid>
	</course>




	<course>
	<clbid>0000002829</clbid>
	<coursestatus>C</coursestatus>
	<deptname>AMST</deptname>
	<coursenumber>208</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>T</coursesubtype>
	<coursename>Top: American Frontier</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;13148&apos;)"&gt;Hahn, Steven C.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0935-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L177&apos;);"&gt;L 177&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000008</crsid>
	</course>




	<course>
	<clbid>0000002830</clbid>
	<coursestatus>O</coursestatus>
	<deptname>AMST</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Amer Magazines</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;4583&apos;)"&gt;Kutulas, Judy&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000012</crsid>
	</course>




	<course>
	<clbid>0000002831</clbid>
	<coursestatus>O</coursestatus>
	<deptname>AMST</deptname>
	<coursenumber>301</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>S</coursesubtype>
	<coursename>Sem: Man and Nature</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;110&apos;)"&gt;Allister, Mark&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;L420&apos;);"&gt;L 420&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000013</crsid>
	</course>




	<course>
	<clbid>0000002832</clbid>
	<coursestatus>O</coursestatus>
	<deptname>AMST</deptname>
	<coursenumber>398</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IR/The Written Amer</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;110&apos;)"&gt;Allister, Mark&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000015</crsid>
	</course>




	<course>
	<clbid>0000003616</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ARMS</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/African-Amer Bio</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2113&apos;)"&gt;Fitzgerald, Michael&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001487</crsid>
	</course>




	<course>
	<clbid>0000003617</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ARMS</deptname>
	<coursenumber>398</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IR/Native Education</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;179&apos;)"&gt;Anderson, Carolyn&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001489</crsid>
	</course>




	<course>
	<clbid>0000002833</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>111</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Perceptual Draw</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7064&apos;)"&gt;Saurer, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0800-0925</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC216&apos;);"&gt;DC 216&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000019</crsid>
	</course>




	<course>
	<clbid>0000002834</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>112</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Conceptual Draw</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7064&apos;)"&gt;Saurer, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0110PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC216&apos;);"&gt;DC 216&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000020</crsid>
	</course>




	<course>
	<clbid>0000002835</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>113</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Color Design</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;276&apos;)"&gt;Arneson, Wendell&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC116&apos;);"&gt;DC 116&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000021</crsid>
	</course>




	<course>
	<clbid>0000002836</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>113</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Color Design</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;276&apos;)"&gt;Arneson, Wendell&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1045-1140</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC116&apos;);"&gt;DC 116&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000021</crsid>
	</course>




	<course>
	<clbid>0000002837</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>114</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Foundation Sculpture</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1369&apos;)"&gt;Dell, Irve&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0935-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC106&apos;);"&gt;DC 106&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000022</crsid>
	</course>




	<course>
	<clbid>0000002838</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>119</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Ceramics: Wheel</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0935-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC115E&apos;);"&gt;DC 115E&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000026</crsid>
	</course>




	<course>
	<clbid>0000002839</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>124</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Photography</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5816&apos;)"&gt;Ojala, Margaret&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0800-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC102&apos;);"&gt;DC 102&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000029</crsid>
	</course>




	<course>
	<clbid>0000002840</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>151</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Renaissance--Present</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;14183&apos;)"&gt;Van Schepen, Randall&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0905-1000</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC305&apos;);"&gt;DC 305&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000032</crsid>
	</course>




	<course>
	<clbid>0000002841</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>222</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Watercolor Painting</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;276&apos;)"&gt;Arneson, Wendell&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1255-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC116&apos;);"&gt;DC 116&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000034</crsid>
	</course>




	<course>
	<clbid>0000002842</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>224</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Sculpt: Metal Direct</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1369&apos;)"&gt;Dell, Irve&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC105&apos;);"&gt;DC 105&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000036</crsid>
	</course>




	<course>
	<clbid>0000002843</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>225</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Arch Drawing/Design I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1564&apos;)"&gt;Edwins, Steven&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0800-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC116&apos;);"&gt;DC 116&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000037</crsid>
	</course>




	<course>
	<clbid>0000002844</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>227</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Printmkg: Intaglio/Mono</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7486&apos;)"&gt;Shoger, Jan&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1045-1245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC212&apos;);"&gt;DC 212&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000039</crsid>
	</course>




	<course>
	<clbid>0000002845</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>234</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Ceramics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 1145-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC115C&apos;);"&gt;DC 115C&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000045</crsid>
	</course>




	<course>
	<clbid>0000002846</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>238</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Photography</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5816&apos;)"&gt;Ojala, Margaret&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1255-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC102&apos;);"&gt;DC 102&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000046</crsid>
	</course>




	<course>
	<clbid>0000002847</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>239</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Video Art Production</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;13038&apos;)"&gt;Ryan, David E.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0800-1100</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC100&apos;);"&gt;DC 100&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000047</crsid>
	</course>




	<course>
	<clbid>0000002848</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>253</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Art Since 1950</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;14183&apos;)"&gt;Van Schepen, Randall&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 1045-1140</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC305&apos;);"&gt;DC 305&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000052</crsid>
	</course>




	<course>
	<clbid>0000002851</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>275</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>T</coursesubtype>
	<coursename>Topics in Art History</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;13137&apos;)"&gt;Thompson, Nancy M.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0120-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC204&apos;);"&gt;DC 204&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000066</crsid>
	</course>




	<course>
	<clbid>0000002852</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Renaissance Art</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;13137&apos;)"&gt;Thompson, Nancy M.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000002853</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Functional Ceramic</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000002854</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Photography</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5816&apos;)"&gt;Ojala, Margaret&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000002855</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>C</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Advanced Painting</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;276&apos;)"&gt;Arneson, Wendell&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000002856</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>D</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Watercolor Design</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;276&apos;)"&gt;Arneson, Wendell&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000002857</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>E</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Promo W/Dig Arts</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;276&apos;)"&gt;Arneson, Wendell&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000002858</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>F</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Printmaking</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;7486&apos;)"&gt;Shoger, Jan&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000069</crsid>
	</course>




	<course>
	<clbid>0000002859</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>343</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Sr Studies/Studio Art</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2492&apos;)"&gt;Gallas, Ron&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>Th 0700-1000PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC305&apos;);"&gt;DC 305&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000071</crsid>
	</course>




	<course>
	<clbid>0000002860</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>395</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Sr Studies-Art Hist</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;13137&apos;)"&gt;Thompson, Nancy M.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0120-0245PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC204&apos;);"&gt;DC 204&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000074</crsid>
	</course>




	<course>
	<clbid>0000002861</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>398</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IR/Painting</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;276&apos;)"&gt;Arneson, Wendell&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000075</crsid>
	</course>




	<course>
	<clbid>0000002862</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>112</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>The West &amp;amp; East Asia</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;1821&apos;)"&gt;Entenmann, Robert&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MWF 0200-0255PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;H307&apos;);"&gt;H 307&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000077</crsid>
	</course>




	<course>
	<clbid>0000002863</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>235</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Modrn Japanese Lit-Tr</coursename>
	<pn>N</pn>
	<notes></notes>