<?xml version="1.0"?>

<!DOCTYPE searchresults [
        <!ELEMENT course (clbid, coursestatus, deptname, coursenumber, coursesection, coursesubtype, coursename, pn, notes, instructors, halfcredit, credits, meetingtimes, gereqs, meetinglocations, varcredits, groupid, grouptype)>
	<!ELEMENT clbid (#PCDATA)>
	<!ELEMENT coursestatus (#PCDATA)>
	<!ELEMENT coursename (#PCDATA)>
	<!ELEMENT deptname (#PCDATA)>
	<!ELEMENT coursesection (#PCDATA)>
	<!ELEMENT coursesubtype (#PCDATA)>
	<!ELEMENT pn (#PCDATA)>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT instructors (#PCDATA)>
	<!ELEMENT halfcredit (#PCDATA)>
	<!ELEMENT credits (#PCDATA)>
	<!ELEMENT meetingtimes (#PCDATA)>
	<!ELEMENT gereqs (#PCDATA)>
	<!ELEMENT meetinglocations (#PCDATA)>
	<!ELEMENT varcredits (#PCDATA)>
	<!ELEMENT groupid (#PCDATA)>
	<!ELEMENT grouptype (#PCDATA)>
	<!ELEMENT crsid (#PCDATA)>
]>
<searchresults>




	<course>
	<clbid>0000007508</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>110</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Foundation Drawing</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC216&apos;);"&gt;DC 216&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000018</crsid>
	</course>




	<course>
	<clbid>0000007509</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>121</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Foundations Ceramics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC115E&apos;);"&gt;DC 115E&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001496</crsid>
	</course>




	<course>
	<clbid>0000007510</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>124</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Found Photography</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC102&apos;);"&gt;DC 102&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000029</crsid>
	</course>




	<course>
	<clbid>0000007511</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>151</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Renaissance--Present</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC204&apos;);"&gt;DC 204&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000032</crsid>
	</course>




	<course>
	<clbid>0000007512</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>121</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Asian Cultures</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML515&apos;);"&gt;RML 515&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000078</crsid>
	</course>




	<course>
	<clbid>0000007513</clbid>
	<coursestatus>O</coursestatus>
	<deptname>BIO</deptname>
	<coursenumber>121</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Biological Science</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930&lt;br&gt;T 0100-0500PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC278&apos;);"&gt;SC 278&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC273&apos;);"&gt;SC 273&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000100</crsid>
	</course>




	<course>
	<clbid>0000007514</clbid>
	<coursestatus>O</coursestatus>
	<deptname>BIO</deptname>
	<coursenumber>233</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Intermediate Genetics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130&lt;br&gt;WTh 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC274&apos;);"&gt;SC 274&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC211&apos;);"&gt;SC 211&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000122</crsid>
	</course>




	<course>
	<clbid>0000007515</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>247</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Organic Chemistry</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC378&apos;);"&gt;SC 378&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000196</crsid>
	</course>




	<course>
	<clbid>0000007516</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>253</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>L</coursesubtype>
	<coursename>Synthesis Lab</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>MT 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC311&apos;);"&gt;SC 311&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000199</crsid>
	</course>




	<course>
	<clbid>0000007519</clbid>
	<coursestatus>O</coursestatus>
	<deptname>DNCTE</deptname>
	<coursenumber>121</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Ballet I</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC_STUDIO_2&apos;);"&gt;DC _STUDIO_2&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000353</crsid>
	</course>




	<course>
	<clbid>0000007517</clbid>
	<coursestatus>O</coursestatus>
	<deptname>EDUC</deptname>
	<coursenumber>314</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Soc St-Elem Classroom</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0900-1200PM&lt;br&gt;M-F 0100-0300PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH10L&apos;);"&gt;FH 10L&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH10L&apos;);"&gt;FH 10L&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000315</crsid>
	</course>




	<course>
	<clbid>0000007518</clbid>
	<coursestatus>O</coursestatus>
	<deptname>EDUC</deptname>
	<coursenumber>315</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Reading Comm Literacy</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0900-1200PM&lt;br&gt;M-F 0100-0300PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH10L&apos;);"&gt;FH 10L&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;FH10L&apos;);"&gt;FH 10L&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000316</crsid>
	</course>




	<course>
	<clbid>0000007520</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>247</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Post-Colonial Lit</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML525&apos;);"&gt;RML 525&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000411</crsid>
	</course>




	<course>
	<clbid>0000007521</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>275</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Literature &amp;amp; Film</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML525&apos;);"&gt;RML 525&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000424</crsid>
	</course>




	<course>
	<clbid>0000007522</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>283</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Studies in Prose</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML525&apos;);"&gt;RML 525&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000429</crsid>
	</course>




	<course>
	<clbid>0000007523</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>347</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>T</coursesubtype>
	<coursename>Top: Post Colonial Lit</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML525&apos;);"&gt;RML 525&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000438</crsid>
	</course>




	<course>
	<clbid>0000007526</clbid>
	<coursestatus>O</coursestatus>
	<deptname>FAMST</deptname>
	<coursenumber>242</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Family Relationships</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;OM002&apos;);"&gt;OM 002&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000649</crsid>
	</course>




	<course>
	<clbid>0000007527</clbid>
	<coursestatus>O</coursestatus>
	<deptname>FAMST</deptname>
	<coursenumber>253</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Human Sexuality</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;OM002&apos;);"&gt;OM 002&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000651</crsid>
	</course>




	<course>
	<clbid>0000007524</clbid>
	<coursestatus>O</coursestatus>
	<deptname>GERM</deptname>
	<coursenumber>231</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Intermed German I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000508</crsid>
	</course>




	<course>
	<clbid>0000007525</clbid>
	<coursestatus>O</coursestatus>
	<deptname>GERM</deptname>
	<coursenumber>232</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Intermed German II</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000509</crsid>
	</course>




	<course>
	<clbid>0000007528</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MATH</deptname>
	<coursenumber>120</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Calculus I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000731</crsid>
	</course>




	<course>
	<clbid>0000007529</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MATH</deptname>
	<coursenumber>210</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Principles of Math</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;OM001&apos;);"&gt;OM 001&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000735</crsid>
	</course>




	<course>
	<clbid>0000007530</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MATH</deptname>
	<coursenumber>252</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Abstract Algebra I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000747</crsid>
	</course>




	<course>
	<clbid>0000007531</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MATH</deptname>
	<coursenumber>388</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>S</coursesubtype>
	<coursename>Sem: Hist/Phil of Math</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000764</crsid>
	</course>




	<course>
	<clbid>0000007532</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MGMT</deptname>
	<coursenumber>294</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Academic Internship</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;15837&apos;)"&gt;Kramer, Daniel B.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000784</crsid>
	</course>




	<course>
	<clbid>0000007533</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>103</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Golf</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000997</crsid>
	</course>




	<course>
	<clbid>0000007534</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>106</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Rock Climbing</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;TC&apos;);"&gt;TC&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000998</crsid>
	</course>




	<course>
	<clbid>0000007535</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>126</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Scuba Diving</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001008</crsid>
	</course>




	<course>
	<clbid>0000007536</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>133</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Individual Fitness.50</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0645-0745</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;TC&apos;);"&gt;TC&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001012</crsid>
	</course>




	<course>
	<clbid>0000007537</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PEAC</deptname>
	<coursenumber>140</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Wt Training Co-Ed .50</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0645-0745</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;TC&apos;);"&gt;TC&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001016</crsid>
	</course>




	<course>
	<clbid>0000007538</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PHYS</deptname>
	<coursenumber>124</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Principles Physics I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130&lt;br&gt;WTh 0100-0330PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC170&apos;);"&gt;SC 170&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC111&apos;);"&gt;SC 111&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001072</crsid>
	</course>




	<course>
	<clbid>0000007539</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSCI</deptname>
	<coursenumber>252</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Politics &amp;amp; Developmnt</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;HH403&apos;);"&gt;HH 403&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001122</crsid>
	</course>




	<course>
	<clbid>0000007540</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSYCH</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Alcohol Adolescent</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;15747&apos;)"&gt;Dickinson, Shelly D.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001179</crsid>
	</course>




	<course>
	<clbid>0000007541</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>225</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>God &amp;amp; Human Suffering</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC129&apos;);"&gt;SC 129&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001209</crsid>
	</course>




	<course>
	<clbid>0000007542</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>289</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Buddhism,Peace,Justic</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML515&apos;);"&gt;RML 515&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001234</crsid>
	</course>




	<course>
	<clbid>0000007543</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Faith and Works</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;15819&apos;)"&gt;Schillinger, Jamie A.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001239</crsid>
	</course>




	<course>
	<clbid>0000007545</clbid>
	<coursestatus>O</coursestatus>
	<deptname>STAT</deptname>
	<coursenumber>110</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Prin of Statistics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SC184&apos;);"&gt;SC 184&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001402</crsid>
	</course>




	<course>
	<clbid>0000007544</clbid>
	<coursestatus>O</coursestatus>
	<deptname>THEAT</deptname>
	<coursenumber>100</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Oral Interpretation</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;&apos;)"&gt;Staff&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>