<?xml version="1.0"?>

<!DOCTYPE searchresults [
        <!ELEMENT course (clbid, coursestatus, deptname, coursenumber, coursesection, coursesubtype, coursename, pn, notes, instructors, halfcredit, credits, meetingtimes, gereqs, meetinglocations, varcredits, groupid, grouptype)>
	<!ELEMENT clbid (#PCDATA)>
	<!ELEMENT coursestatus (#PCDATA)>
	<!ELEMENT coursename (#PCDATA)>
	<!ELEMENT deptname (#PCDATA)>
	<!ELEMENT coursesection (#PCDATA)>
	<!ELEMENT coursesubtype (#PCDATA)>
	<!ELEMENT pn (#PCDATA)>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT instructors (#PCDATA)>
	<!ELEMENT halfcredit (#PCDATA)>
	<!ELEMENT credits (#PCDATA)>
	<!ELEMENT meetingtimes (#PCDATA)>
	<!ELEMENT gereqs (#PCDATA)>
	<!ELEMENT meetinglocations (#PCDATA)>
	<!ELEMENT varcredits (#PCDATA)>
	<!ELEMENT groupid (#PCDATA)>
	<!ELEMENT grouptype (#PCDATA)>
	<!ELEMENT crsid (#PCDATA)>
]>
<searchresults>




	<course>
	<clbid>0000091407</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ART</deptname>
	<coursenumber>207</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Ceramics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;10981&apos;)"&gt;Fisher, Kathryne&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/ALS-A.pdf"&gt;ALS-A&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;DC115&apos;);"&gt;DC 115&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001496</crsid>
	</course>




	<course>
	<clbid>0000091408</clbid>
	<coursestatus>X</coursestatus>
	<deptname>ASIAN</deptname>
	<coursenumber>130</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Japanese SciFi/Glob Persp</coursename>
	<pn>N</pn>
	<notes>This course has been canceled.</notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;23541&apos;)"&gt;Bridges IV, William H.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/ALS-L.pdf"&gt;ALS-L&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/MCG.pdf"&gt;MCG&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype>R</grouptype>
	<crsid>0000022785</crsid>
	</course>




	<course>
	<clbid>0000088038</clbid>
	<coursestatus>O</coursestatus>
	<deptname>BIO</deptname>
	<coursenumber>125</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Cell Bio &amp;amp; Genetics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2593&apos;)"&gt;Giannini, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/IST.pdf"&gt;IST&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/SED.pdf"&gt;SED&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS390&apos;);"&gt;RNS 390&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid>0000000106</groupid>
	<grouptype></grouptype>
	<crsid>0000000106</crsid>
	</course>




	<course>
	<clbid>0000088039</clbid>
	<coursestatus>O</coursestatus>
	<deptname>BIO</deptname>
	<coursenumber>125</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>L</coursesubtype>
	<coursename>Cell Bio &amp;amp; Genetics Lab</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;2593&apos;)"&gt;Giannini, John&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.00</credits>
	<gereqs></gereqs>
	<meetingtimes>W 0100-0500PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS255&apos;);"&gt;RNS 255&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid>0000000106</groupid>
	<grouptype></grouptype>
	<crsid>0000000107</crsid>
	</course>




	<course>
	<clbid>0000092240</clbid>
	<coursestatus>O</coursestatus>
	<deptname>BIO</deptname>
	<coursenumber>128</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Water:Prec, Precar, &amp;amp;Prob</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;8768&apos;)"&gt;Van Wylen, David&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/IST.pdf"&gt;IST&lt;/a&gt; ('08)</gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype>R</grouptype>
	<crsid>0000025184</crsid>
	</course>




	<course>
	<clbid>0000092045</clbid>
	<coursestatus>C</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>123</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Atom/Molec Structure</coursename>
	<pn>N</pn>
	<notes>This course is a special offering.</notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;14194&apos;)"&gt;Riley, Patrick N.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS310&apos;);"&gt;RNS 310&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000189</crsid>
	</course>




	<course>
	<clbid>0000091379</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>125</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Struct Chem &amp;amp; Equilib</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;14194&apos;)"&gt;Riley, Patrick N.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/SED.pdf"&gt;SED&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS310&apos;);"&gt;RNS 310&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid>0000000192</groupid>
	<grouptype></grouptype>
	<crsid>0000000192</crsid>
	</course>




	<course>
	<clbid>0000091380</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>125</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>L</coursesubtype>
	<coursename>Struct Chem &amp;amp; Equilib Lab</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;14194&apos;)"&gt;Riley, Patrick N.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.00</credits>
	<gereqs></gereqs>
	<meetingtimes>MW 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS355&apos;);"&gt;RNS 355&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid>0000000192</groupid>
	<grouptype></grouptype>
	<crsid>0000000193</crsid>
	</course>




	<course>
	<clbid>0000091389</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>247</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Organic Chemistry I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6161&apos;)"&gt;Pearson, Wesley&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS310&apos;);"&gt;RNS 310&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid>0000000196</groupid>
	<grouptype></grouptype>
	<crsid>0000000196</crsid>
	</course>




	<course>
	<clbid>0000091390</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>253</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>L</coursesubtype>
	<coursename>Synthesis Lab I</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;23817&apos;)"&gt;Terrell, Cassidy R.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>TTh 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS340&apos;);"&gt;RNS 340&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid>0000000196</groupid>
	<grouptype></grouptype>
	<crsid>0000000199</crsid>
	</course>




	<course>
	<clbid>0000091391</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>253</coursenumber>
	<coursesection>B</coursesection>
	<coursesubtype>L</coursesubtype>
	<coursename>Synthesis Lab I</coursename>
	<pn>Y</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;23817&apos;)"&gt;Terrell, Cassidy R.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.25</credits>
	<gereqs></gereqs>
	<meetingtimes>MW 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS340&apos;);"&gt;RNS 340&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid>0000000196</groupid>
	<grouptype></grouptype>
	<crsid>0000000199</crsid>
	</course>




	<course>
	<clbid>0000091473</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CHEM</deptname>
	<coursenumber>379</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Biochemistry I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;25&apos;)"&gt;Abdella, Beth&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/IST.pdf"&gt;IST&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;TOH182&apos;);"&gt;TOH 182&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000214</crsid>
	</course>




	<course>
	<clbid>0000092109</clbid>
	<coursestatus>C</coursestatus>
	<deptname>CSCI</deptname>
	<coursenumber>390</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>S</coursesubtype>
	<coursename>Sem: Senior Capstone</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;806&apos;)"&gt;Brown, Richard&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000305</crsid>
	</course>




	<course>
	<clbid>0000092110</clbid>
	<coursestatus>O</coursestatus>
	<deptname>CSCI</deptname>
	<coursenumber>398</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IR/HPC in Context</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;806&apos;)"&gt;Brown, Richard&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000307</crsid>
	</course>




	<course>
	<clbid>0000091482</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>206</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>T</coursesubtype>
	<coursename>Top: African Literature</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5144&apos;)"&gt;Mbele, Joseph L.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/ALS-L.pdf"&gt;ALS-L&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/MCG.pdf"&gt;MCG&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML520&apos;);"&gt;RML 520&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype>R</grouptype>
	<crsid>0000021392</crsid>
	</course>




	<course>
	<clbid>0000091483</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>210</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Post-Colonial Lit</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5144&apos;)"&gt;Mbele, Joseph L.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/ALS-L.pdf"&gt;ALS-L&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/MCG.pdf"&gt;MCG&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 0230-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RML520&apos;);"&gt;RML 520&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000411</crsid>
	</course>




	<course>
	<clbid>0000092104</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ENGL</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/19-20 C Am Lit Styles</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;22837&apos;)"&gt;Gallego, Carlos&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000434</crsid>
	</course>




	<course>
	<clbid>0000091749</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ES/PS</deptname>
	<coursenumber>225</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Env Political Theory</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;15825&apos;)"&gt;Lott, Anthony&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/EIN.pdf"&gt;EIN&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/WRI.pdf"&gt;WRI&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;HH319&apos;);"&gt;HH 319&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000458</crsid>
	</course>




	<course>
	<clbid>0000091418</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ESAC</deptname>
	<coursenumber>133</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Individual Fitness.50</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;11465&apos;)"&gt;Ludwig, Michael M.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/SPM.pdf"&gt;SPM&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 0230-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;TBA&apos;);"&gt;TBA&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001012</crsid>
	</course>




	<course>
	<clbid>0000091417</clbid>
	<coursestatus>O</coursestatus>
	<deptname>ESAC</deptname>
	<coursenumber>140</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Wt Training Co-Ed .50</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;14953&apos;)"&gt;McCarthy, Robert K.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>0.50</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/SPM.pdf"&gt;SPM&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;SAC112&apos;);"&gt;SAC 112&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001016</crsid>
	</course>




	<course>
	<clbid>0000092131</clbid>
	<coursestatus>C</coursestatus>
	<deptname>GERM</deptname>
	<coursenumber>232</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Intermed German II</coursename>
	<pn>N</pn>
	<notes>This course is a special offering.</notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6671&apos;)"&gt;Rippley, Lavern&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/FOL-G.pdf"&gt;FOL-G&lt;/a&gt; ('08)</gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000509</crsid>
	</course>




	<course>
	<clbid>0000092099</clbid>
	<coursestatus>C</coursestatus>
	<deptname>ID</deptname>
	<coursenumber>250</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Res Opp Science for Sophs</coursename>
	<pn>N</pn>
	<notes>Prerequisite: completion of Summer Bridge program or permission of instructor.</notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;6658&apos;)"&gt;Richey, Matthew&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;8616&apos;)"&gt;Umbanhowar, Charles Jr.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1100-1200PM&lt;br&gt;TTh 0100-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS400&apos;);"&gt;RNS 400&lt;/a&gt;&lt;br&gt;&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS400&apos;);"&gt;RNS 400&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype>R</grouptype>
	<crsid>0000026897</crsid>
	</course>




	<course>
	<clbid>0000091526</clbid>
	<coursestatus>O</coursestatus>
	<deptname>MUSIC</deptname>
	<coursenumber>223</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Composition I</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;5013&apos;)"&gt;Mahr, Timothy&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;CHM224&apos;);"&gt;CHM 224&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000000822</crsid>
	</course>




	<course>
	<clbid>0000091956</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSCI</deptname>
	<coursenumber>111</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>American Politics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;23508&apos;)"&gt;Anderson, Joshua&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/HBS.pdf"&gt;HBS&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/MCD.pdf"&gt;MCD&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;HH302&apos;);"&gt;HH 302&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001103</crsid>
	</course>




	<course>
	<clbid>0000091750</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSCI</deptname>
	<coursenumber>285</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>International Law</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;15825&apos;)"&gt;Lott, Anthony&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/HWC.pdf"&gt;HWC&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/ORC.pdf"&gt;ORC&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;HH319&apos;);"&gt;HH 319&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001138</crsid>
	</course>




	<course>
	<clbid>0000091400</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSYCH</deptname>
	<coursenumber>125</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Principles: Psych</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;20155&apos;)"&gt;Ori&#xf1;a, M. Minda&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/HBS.pdf"&gt;HBS&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/IST.pdf"&gt;IST&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1000-1130</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS124&apos;);"&gt;RNS 124&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001154</crsid>
	</course>




	<course>
	<clbid>0000091399</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSYCH</deptname>
	<coursenumber>249</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>Social Psychology</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;20155&apos;)"&gt;Ori&#xf1;a, M. Minda&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/HBS.pdf"&gt;HBS&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 0800-0930</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;RNS124&apos;);"&gt;RNS 124&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001170</crsid>
	</course>




	<course>
	<clbid>0000092105</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSYCH</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Psychology of PTSD</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;19398&apos;)"&gt;Davenport, Nicholas D.&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001179</crsid>
	</course>




	<course>
	<clbid>0000092186</clbid>
	<coursestatus>O</coursestatus>
	<deptname>PSYCH</deptname>
	<coursenumber>298</coursenumber>
	<coursesection>A</coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Psycholinguistics</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;21097&apos;)"&gt;Loebach, Jeremy&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001179</crsid>
	</course>




	<course>
	<clbid>0000091457</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>223</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>St. Paul/Letter/Gospel</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;3061&apos;)"&gt;Hanson, James&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/BTS-T.pdf"&gt;BTS-T&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/WRI.pdf"&gt;WRI&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 1230-0200PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;OM110&apos;);"&gt;OM 110&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001207</crsid>
	</course>




	<course>
	<clbid>0000091459</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>276</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>The Ethics of Jesus</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;3061&apos;)"&gt;Hanson, James&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs>&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/EIN.pdf"&gt;EIN&lt;/a&gt; ('08)&lt;br&gt;&lt;a class="sis-nounderline" target="bottom" href="http://www.stolaf.edu/committees/curriculum/ge/WRI.pdf"&gt;WRI&lt;/a&gt; ('08)</gereqs>
	<meetingtimes>M-F 0230-0400PM</meetingtimes>
	<meetinglocations>&lt;a class="sis-nounderline" href="JavaScript:sis_roominfo_openwindow(&apos;OM110&apos;);"&gt;OM 110&lt;/a&gt;</meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001232</crsid>
	</course>




	<course>
	<clbid>0000092188</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>298</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>
	<coursename>IS/Interdialogue &amp;amp; Peace</coursename>
	<pn>N</pn>
	<notes></notes>
	<instructors>&lt;a class="sis-nounderline" href="JavaScript:sis_facinfo_openwindow(&apos;9090&apos;)"&gt;Wilson, Charles&lt;/a&gt;</instructors>
	<halfcredit></halfcredit>
	<credits>1.00</credits>
	<gereqs></gereqs>
	<meetingtimes></meetingtimes>
	<meetinglocations></meetinglocations>
	<varcredits>N</varcredits>
	<groupid></groupid>
	<grouptype></grouptype>
	<crsid>0000001239</crsid>
	</course>




	<course>
	<clbid>0000092184</clbid>
	<coursestatus>O</coursestatus>
	<deptname>REL</deptname>
	<coursenumber>398</coursenumber>
	<coursesection></coursesection>
	<coursesubtype>R</coursesubtype>